### ISSUE TITLE
pdflatex command barfs on valid input

### ISSUE THREAD

**Issue by ORESoftware** [tex-mirror/pdftex#1]
I have this command:

```
pandoc ./test.html  -t latex | pdflatex  >  ./test.pdf
```

the `test.html` file ils like so:

```
<html>
 <div>hi</div>
 <p class="tab">Example of a  tab</p>
</html>
```

but when I run the command I get this output in test.pdf:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
**entering extended mode
! I can't find file `hi'.
<*> hi
      
(Press Enter to retry, or Control-D to exit)
Please type another input file name: ! I can't find file `hi'.
<*> hi
      
(Press Enter to retry, or Control-D to exit)
Please type another input file name: ! I can't find file `Example'.
<*> hi
      
(Press Enter to retry, or Control-D to exit)
Please type another input file name: 
! Emergency stop.
<*> hi
      
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on texput.log.

```

the intermediate output is:

```
hi

Example of a tab
```

so something seems wrong with the `pdflatex` command? If this is not the right place to file a bug, please direct me to the right place! ty

**Comment by ORESoftware** [comment]
fwiw, this yields the same error:

```
pandoc ./test.html  -t latex  | xelatex  >  ./test.pdf
```

**Comment by tbodt** [comment]
This is just a mirror of pdftex, not an official repository. But I think your problem is that TeX doesn't take input through stdin the way you expect. After all, it was written in Pascal in 1978, on a hacked version of DEC's operating system used only at Stanford, before modern concepts such as "standard input" were widely used. Just use a temporary file.

**Comment by tbodt** [comment]
If you still want to file a bug report or need someone to talk to, check out tug.org.
